### ISSUE TITLE
Feature: Select default page

### ISSUE THREAD

**Issue by Svenum** [logseq/publish-spa#30]
I would love to be able to select an default page that loads up if a user go to the website.
Sou youu would be able to link to the importent pages or create an inventory list so that the user could find quicker what he searches. Is this possible?

Something like here: https://docs.logseq.com/
It automatically redirects to the page "content" and even had an little "house logo" on the site for the main page.

And as little extra I would love to see the option, that the sidebar is default visible.

**Comment by mlhiter** [comment]
@Svenum 
### For default page: 
you can go into your logseq setting-general edit `config.edn`,in it add this and modify it for what you want.
```edn
:default-home {:page "overview"
               :sidebar "Contents"  }
```
you can understand this i know.

### For the sidebar is default visible: 
Maybe these option can help,i donnot know because i have not tried.
![image](https://github.com/logseq/publish-spa/assets/100181513/22b22a90-30dc-4212-8a23-4413a4d0e147)

**Comment by Svenum** [comment]
Worked for me. But I dont found an option to add the page at the top of the left sidebar like in the example I shared.

**Comment by logseq-cldwalker** [comment]
There isn't an option for adding pages to the top. You can favorite a page and it will appear in the left sidebar

**Comment by Svenum** [comment]
Ok, that is fine for me.
