### ISSUE TITLE
A default new graph doesn't publish content

### ISSUE THREAD

**Issue by pwright** [logseq/publish-spa#9]
### What Happened?

After creating a new graph (0.9.8), pushing to github, setting up with publish-spa, the results don't show any content, eg
https://pwright.github.io/cost-experiment/#/all-pages

### Reproduce the Bug

1. Create graph
2. push to github
3. set up publish spa
4. enable Pages
5. view result

### Expected Behavior

A reported error would be nice if the solution isn't easy, but a workaround is to replace the new graph config.edn with https://github.com/logseq/publish-spa/blob/main/test/publish-test-graph/logseq/config.edn

### Desktop or Mobile Platform Information

Logseq 0.9.8

**Comment by logseq-cldwalker** [comment]
Hi. I'm not following how this would report an error. The empty behavior is working as configured since pages are not public by default. Perhaps are you asking to make this action more friendly for a first time user? If so, I could some add docs or link to relevant parts of https://docs.logseq.com/#/page/publishing

**Comment by pwright** [comment]
@logseq-cldwalker How embarrassing, I forgot to make the graph public!

**Comment by logseq-cldwalker** [comment]
No worries. I've updated the readme to link to the publishing doc to help
others in the future
